### ISSUE TITLE
执行 yarn 之后，下载依赖失败

### ISSUE THREAD

**Issue by brownchow** [HeiSir2014/M3U8-Downloader#15]
error /home/brown/code/github-projects/M3U8-Downloader/node_modules/electron: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /home/brown/code/github-projects/M3U8-Downloader/node_modules/electron
Output:
RequestError: connect ETIMEDOUT 52.74.223.119:443
    at ClientRequest.<anonymous> (/home/brown/code/github-projects/M3U8-Downloader/node_modules/@electron/get/node_modules/got/source/request-as-event-emitter.js:178:14)
    at Object.onceWrapper (node:events:514:26)
    at ClientRequest.emit (node:events:406:35)
    at ClientRequest.origin.emit (/home/brown/code/github-projects/M3U8-Downloader/node_modules/@electron/get/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at TLSSocket.socketErrorListener (node:_http_client:447:9)
    at TLSSocket.emit (node:events:394:28)
    at emitErrorNT (node:internal/streams/destroy:193:8)
    at emitErrorCloseNT (node:internal/streams/destroy:158:3)

**Comment by brownchow** [comment]
挂代理，可以了
